version: '3'
services:
  frontend:
    build:
      context: ./front/my-app
    networks:
      - app_network

  backend1:
    build:
      context: ./back1
    networks:
      - app_network

  backend2:
    build:
      context: ./back2
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx  # Pointing to the directory with the Dockerfile and nginx.conf
    ports:
      - "80:80"  # Exposing Nginx on port 80 of the host machine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Ensure Nginx uses your custom config
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
